### ISSUE TITLE
Error when converting schema with if / then

### ISSUE THREAD

**Issue by nathalie** [openapi-contrib/json-schema-to-openapi-schema#27]
Hi, I get an error when I try to convert the schema attached
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["css", "js", "i18n", "json"]
    },
    "locale": {
      "type": "string"
    }
  },
  "if": {
    "properties": {
      "type": {
        "const": "i18n"
      }
    }
  },
  "then": {
    "required": ["locale"]
  }
}
```

TypeError: Cannot convert undefined or null to object
    at stripIllegalKeywords (/home/nathalie/projects/focus/test-open-api/node_modules/@openapi-contrib/json-schema-to-openapi-schema/index.js:48:2)
    at convertSchema (/home/nathalie/projects/focus/test-open-api/node_modules/@openapi-contrib/json-schema-to-openapi-schema/index.js:55:11)
    at _apply (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:270:14)
    at Object._processArrayOfSchemas (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:173:5)
    at _processSchemaKeyword (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:146:24)
    at subschemaWalk (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:102:7)
    at _apply (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:283:3)
    at Object._processArrayOfSchemas (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:173:5)
    at _processSchemaKeyword (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:146:24)
    at subschemaWalk (/home/nathalie/projects/focus/test-open-api/node_modules/@cloudflare/json-schema-walker/lib/schemaWalk.js:102:7)

**Comment by jonluca** [comment]
This is fixed in this PR https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/29

It is also deployed on npm as `browser-json-schema-to-openapi-schema`, but hopefully the PR will be accepted and we can cut a release for this package soon

**Comment by nathalie** [comment]
Hi Jonluca, is it possible that with the latest version, I can no longer reference a definition inside another one? I saw you also added support for dereferencing definitions, so possibly this is a related side effect? Or is it intended?

**Comment by jonluca** [comment]
Do you have an example?

**Comment by jonluca** [comment]
Ah yes, looks like this is an issue with the new `definitions` crawler.

I fixed it in this PR, but for now you can set `options.convertUnreferencedDefinitions = false` to get around it.
https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/35

**Comment by nathalie** [comment]
That works! Thanks a lot for fixing this.
